{\rtf1\ansi\ansicpg1252\cocoartf2709

\cocoatextscaling0\cocoaplatform0{\fon ttbl\f0\fnil\fcharseto Helvetica Neue;}

{\colortbl;\red255\green255\blue255;\re d246\green246\blue255;\red0\green0\blu e0;}

{\*\expandedcolortbl;;\cssrgb\c97255\c9 7255\c100000;\cssrgb\c0\c0\c0;}

\paperw11900\paperh16840\margl1440\ margr1440\vieww20380\viewh15980\vie wkind0

\deftab720

\pard\pardeftab720\partightenfactor0

\f0\fs37\fsmilli18667 \cf0 \cb2 \expnd0\ expndtw0\kerning0

\outl0\strokewidth0 \strokec3 name: CI\

on: [push, workflow_dispatch]\

jobs:\

build:\
